apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: brainbox
type: Opaque
stringData:
  PORT: "5000"
  JWT_SECRET: "brainbox-secret"
  AWS_REGION: "ap-south-1"
  AWS_ACCESS_KEY_ID: "AKIATMPCN3NFL4WY3VOR"
  AWS_SECRET_ACCESS_KEY: "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"
  ZEN_EMAIL: "leemajosephine3@gmail.com"
  FRONTEND_URL: "http://frontend"
  MONGODB_URI: "mongodb://admin:Admin%40123@mongodb:27017/brainbox?authSource=admin"
